modules/profile/files/devrequire.txt, modules/profile/files/post-merge-dev, modules/profile/files/post-merge-dev-adminlist, modules/profile/files/post-merge-dev-core, modules/profile/files/post-merge-dev-jsonparser, modules/profile/manifests/sopeldev.pp
Install jsonparser & adminlist from source on dev
Switch core to a subdir
Please rm current devcode before deploying
=> sopeldev: configure post-BigChange env

modules/profile/manifests/sopeldev.pp
=> sopeldev: recurse submodules

modules/profile/files/channelmgnt.json
Reverts MirahezeBots/puppet#27
=> Revert "channelmgnt: normalise to lowercase"

.travis.yml
=> add travis check for devrequire.txt

modules/profile/files/channelmgnt.json
=> +channelmgnt config for three channels

modules/phabricator/data/config.yaml
For maintenance, tommorow UK morning
Do not merge until time.
=> phabricator: read only

modules/phabricator/data/config.yaml
Maintenance over
Reverts MirahezeBots/puppet#60
=> Revert "phabricator: read only"

modules/profile/files/post-merge-dev-adminlist, modules/profile/files/post-merge-dev-channelmgnt, modules/profile/files/post-merge-dev-core, modules/profile/files/post-merge-dev-joinall, modules/profile/files/post-merge-dev-jsonparser, modules/profile/files/post-merge-dev-pingpong, modules/profile/manifests/sopeldev.pp
This reverts commit 4215d4cfc27fdf18c4c579d685f8cf314cabd547.
=> Revert "Revert "Update sopeldev.pp (#84)""

modules/profile/manifests/sopeldev.pp, modules/profile/manifests/sopelshared.pp, modules/profile/templates/initscripts/mirahezebotprod.systemd.erb, modules/profile/templates/initscripts/mirahezebottest.systemd.erb
DO NOT MERGE UNLESS sopel user is created.
=> Sopel: isolate under own user

modules/profile/manifests/web.pp
This reverts commit 77ef1eb0e3162528e64b52cd94800904765e1c00.
=> web: absent old site

modules/users/data/data.yaml
=> users: give doug access to view stuff on bots1

modules/users/data/data.yaml
=> users: add sario to tools1/db1

modules/sopel/manifests/init.pp
None of the shared files include private data
=> sopel::init: allow read for other

modules/profile/templates/fhconfig.json
Get new/renamed channels bridged.
=> bridge more channels

modules/users/data/data.yaml
Not needed, was only used once for maintenance
=> users: absent eth

modules/sopel/manifests/prod.pp
Stage 1: absent sopel template
Stage 2: remove files
Please back up after stopping service like done on beta!
=> [DNM] sopel: absent freenode prod (1/2)

modules/profile/manifests/discordirc.pp
Will probably need to rename/delete files when this goes into effect.
Will definately cause restarts of stuff
=> relays: don't duplicate stuff

modules/sopel/files/prodrequire.txt, modules/sopel/manifests/dev.pp
Per https://phab.mirahezebots.org/T205
=> Undeploy pingpong

modules/users/data/data.yaml
No objections by MacFan or Reception.
Old:
- view files as system users
New:
- act as system users
- restart systemd services
=> users: expand Doug's access

modules/sopel/files/channelmgnt.json
=> Add #memipedia-offtopic to list

modules/profile/manifests/discordirc.pp, modules/profile/templates/ballmediaconfig.json
Confirmed with @Agent-Isai that all of these Discord channels are from _one_ Discord server
=> Forked from #239 and #18f460cbd6e0d452a98929900f7e05361bf74b09

modules/profile/templates/fhliberaconfig.json
=> Correct channel ID

modules/phabricator/manifests/init.pp
db2003 is a fake record pointing at db2002
=> phab: add 'replica' db

modules/phabricator/data/config.yaml, modules/phabricator/manifests/init.pp
=> Revert "phab: promote db3001"

modules/phabricator/data/config.yaml, modules/phabricator/manifests/init.pp
Reverts FOSSBots/puppet#331 and b29fb3a3298321483b3ceb6b9019dd79b708bdd3
=> phab: return to LON RW primary DB

modules/phabricator/data/config.yaml, modules/phabricator/manifests/init.pp
=> Revert "phab: temp to boston for reboots"

modules/users/data/data.yaml
=> users: add peer and grant 'ops'

modules/phabricator/data/config.yaml, modules/phabricator/manifests/init.pp
=> Revert "depool london"

modules/users/data/data.yaml
=> users: add chrs to (tools|bot)admins + www-data

modules/users/files/home/peer/.bashrc, modules/users/files/home/peer/.vimrc
i should check my work before using it. :)
=> [users] minor fixes

modules/sopel/files/channelmgnt.json
Per resignation from Miraheze Developers Wiki
=> channelmgnt: remove MacFan4000 from #miraheze-dev

modules/profile/templates/matterbridge.toml
=> mattermost::miraheze: set EditDisable

modules/profile/manifests/discordirc.pp, modules/profile/templates/matterbridge.toml
Reverts FOSSBots/puppet#416
```
[0035] ERROR discord:      could not find Discord server "Miraheze"
[0035]  INFO discord:      Possible server values:
[0035]  INFO discord:      	- Server="Miraheze Community Roles" # by name
[0035]  INFO discord:      	- Server="1006797886027214949" # by ID
[0035] FATAL main:         Starting gateway failed: Bridge discord.mirahezeprivate failed to start: could not find Discord server "Miraheze"
```
=> Revert "Update relay server for Miraheze #cvt-private and #wikicreators"

modules/profile/manifests/discordirc.pp, modules/profile/templates/matterbridge.toml
=> Revert "Revert "Update relay server for Miraheze #cvt-private and #wikicreators""
